-- AlterTable
ALTER TABLE "Bike" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "BikeRating" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "BikeReservation" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
