-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('USER_ROLE_SUPER_ADMIN', 'USER_ROLE_ADMIN', 'USER_ROLE_CLIENT');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "UserRole" NOT NULL DEFAULT E'USER_ROLE_CLIENT';
